# Generated by Django 4.2.5 on 2023-09-05 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramclient',
            name='token_api',
            field=models.CharField(db_index=True, max_length=255, null=True, unique=True),
        ),
    ]
