# Generated by Django 4.2.5 on 2023-09-05 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Message from API')),
                ('auth_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='telegram_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
