# Generated by Django 4.2.5 on 2023-09-05 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrammessage',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
